import type { NextPage } from 'next';
import Head from 'next/head';
import { trpc } from '../utils/trpc';
import { styles } from '../styles/styles';
import Card from '../components/Card';
import PostsCell from '../components/PostsCell';

const Home: NextPage = () => {
  const hello = trpc.useQuery(['example.hello', { text: 'from tRPC' }]);

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.appContainer}>
        <h1 className={styles.title}>
          Create <span className={styles.purple}>T3</span> App
        </h1>
        <p className={styles.body}>This stack uses:</p>

        <div className={styles.grid}>
          <Card name="NextJS" url="https://nextjs.org/" />
          <Card name="TypeScript" url="https://www.typescriptlang.org/" />
          <Card name="TailwindCSS" url="https://tailwindcss.com/" />
          <Card name="tRPC" url="https://trpc.io/" />
        </div>

        <PostsCell />
      </main>
    </>
  );
};

export default Home;
